name: Publish Pypi
on:
  push:
    branches:
      - main
      - alpha

permissions: 
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm install -g semantic-release@23 @semantic-release/exec
      - name: Semantic Release
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
    outputs:
      version: ${{ steps.semantic-release.outputs.release-version }}
      published: ${{ steps.semantic-release.outputs.new-release-published }}

  build:
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.published == 'true' }}
    steps:
    - uses: actions/checkout@v4
    - name: Write version to file
      run: echo ${{ needs.release.outputs.version }} > VERSION.txt
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install hatch
      run: |
        pipx install hatch
    - name: Build
      run: |
        hatch build
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/*
  
  publish:
    runs-on: ubuntu-latest
    needs: build
    environment: release
    permissions: 
      id-token: write
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
