name: Semantic Release
on:
  push:
    branches:
      - main
      - alpha

permissions: 
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Semantic Release
        uses: codfish/semantic-release-action@v3
        id: semantic_release
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_RELEASE }}
        with:
          plugins: |
            [
              "@semantic-release/commit-analyzer",
              "@semantic-release/release-notes-generator",
              "@semantic-release/changelog",
              [
                "@semantic-release/exec",
                {
                  "prepareCmd": "echo ${nextRelease.version} > VERSION.txt",
                }
              ],
              "@semantic-release/git",
              "@semantic-release/github",
            ]
          additional-packages: |
            [
              "@semantic-release/git",
              "@semantic-release/changelog",
              "@semantic-release/exec",
            ]
